# Training Parameters
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 257
PRETRAINED_WEIGHTS: 'IMAGENET1K_V1'
LEARNING_RATE: 0.01
FIND_LR: True
EARLY_STOPPING_PATIENCE: 11
RANDOM_STATE: 42
MODEL_NAME: mobilenet

# Plotting parameters
FIGSIZE: [15, 12]
COLOR_PALETTE: husl
SNS_STYLE: whitegrid


